version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.production
      #    image: cr.selcloud.ru/hexlet/devops-for-programmers-project-74
    image: dsradozhitskiy/devops-for-programmers-project-74
    command: make test
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_NAME: postgres
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: password
      DATABASE_HOST: db
      DATABASE_PORT: 5432
    volumes:
      - app:/app
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  app: