version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.production
#    image: cr.selcloud.ru/hexlet/devops-for-programmers-project-74
    image: dsradozhitskiy/devops-for-programmers-project-74
    command: make test

