version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.production
    image: dsradozhitskiy/devops-for-programmers-project-74
    command: make test
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5